server {
    listen *:80;
    root /var/www/html;
    index /index.php;

    location / {
        try_files $uri /static$uri /index.php&guery_string;
    }

    location ~ \.php$ {
        root /var/www/html/core;

        try_files $uri =404;

        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_pass php-app:9000;
    }
}